### ISSUE TITLE
Copy files to Image

### ISSUE THREAD

**Issue by AngeloBestetti** [richlander/container-workshop#11]
Hi Rich,

Question for you, I just watch your youtube .NET Containers and I didn´t see anything about copying files to the image using the csproj.

I have a .net solution that needs to copy some AI models from another directory, it´s possible?

**Comment by baronfel** [comment]
Hey @AngeloBestetti - the contents of the containers are currently populated from the publish output of your project, so if you ensured the files you wanted were copied to the publish directory (for example, via the [CopyToPublishDirectory](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#copytopublishdirectory) MSBuild metadata on an Item)) then that file would be part of the generated image.

Currently there's no support for creating custom 'layers' in the container with custom data outside of this. This request is similar in aim to https://github.com/dotnet/sdk-container-builds/issues/325 though. If you have some more details about the kinds of experiences you'd like to create that might help guide future development of the container tools!

**Comment by AngeloBestetti** [comment]
I just tried to copy the Yolo AI models to the project and CopyToPublishDirectory and WORKS!!!

Thank you
