### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by ladeak** [richlander/container-workshop#5]
1. What is the best way to deal with certificates? For example, if an organization uses its own "trusted root" and "intermediate root" certificates?
If I install it in the container, when those certs expire, I would need to rebuild the container with the new certs.
If I pull the certificates during app startup, I would need a root user to install the certs.

2. Can I use a `jammy-chiseled` and execute a command during startup with root privileges, and then the app with app privileges?

**Comment by ShawnStoddard** [comment]
Can you use a timestamp authority to extend the lifecycle of your certificates?

**Comment by ladeak** [comment]
I don't think that could work unfortunately.

Note: I wonder how others deal with such situations, what are the best practices around it.

**Comment by richlander** [comment]
The typical approach is to volume mount everything related to certs into the container.

**Comment by ladeak** [comment]
How can we make them trusted without update-ca-certificates?

**Comment by richlander** [comment]
I'm not an expert on this ... However, here's what I would do.

- (regularly) Build certificate store as its own production artifact, with expected tools, like `update-ca-certificates`.
- Copy that onto the host machine as a deployment step.
- Volume mount host certs (in regular or other location) into expected location in container.

**Comment by ladeak** [comment]
Thank you for the suggestion
