### ISSUE TITLE
Composite R2R images.

### ISSUE THREAD

**Issue by voroninp** [richlander/container-workshop#7]
> ASP.NET Core Composite images provide a smaller size on disk while keeping the performance of the default [ReadyToRun (R2R) setting](https://learn.microsoft.com/dotnet/core/deploying/ready-to-run). The caveat is that the composite images have tighter version coupling. This means the final **app** run on them **cannot use handpicked custom versions of the framework and/or ASP.NET assemblies that are built into the composite binary**. For a full technical description on how the composites work, we have a [feature 
doc here](https://github.com/dotnet/runtime/blob/main/docs/design/features/readytorun-composite-format-design.md).

How do I find out which assemblies and of what version?

**Comment by richlander** [comment]
https://github.com/dotnet/aspnetcore/blob/e1758535a7f9922a61a919ebbc26be06f70fa5a1/src/Framework/App.Runtime/src/PartialCompositeAssemblyList.txt

The version is the same version as the rest of the product.

**Comment by voroninp** [comment]
Thanks. So effectively I should not even need to reference these assemblies separately as they are part of ASP.NET metapackage.

**Comment by richlander** [comment]
Right. Zero user gesture required. It's all automatic.
