### ISSUE TITLE
Update examples for 8.0.200

### ISSUE THREAD

**Issue by baronfel** [richlander/container-workshop#8]
Broadly, we should

* remove usage of the NuGet packages and ensure console examples add `EnableSdkContainerSupport` set to true, since 8.0.200 includes the package but requires that enablement flag for non-Web-or-Worker projects
* ensure all publishing uses the `/t:PublishContainer` form instead of the `/p PublishProfile=DefaultContainer` form.

**Comment by richlander** [comment]
We could also use this juncture to move this content somewhere more official.
